### ISSUE TITLE
Have bug!! can't follow.

### ISSUE THREAD

**Issue by MarkKh** [madecodingcomlab/website#2]
<img width="521" alt="Screenshot 2021-06-28 235822" src="https://user-images.githubusercontent.com/85799327/123675417-e2ea3700-d86c-11eb-87fd-2f369418343e.png">

**Comment by KanapongAiamtip** [comment]
I need  fix some bug in Firestone I think it fix it on Version 1.0.0

**Comment by KanapongAiamtip** [comment]
Now Website codee.club Fix now  0.0.10  Have New Features Stats Abbreviate using shortscale (k, M, B, etc) And  Bug Fixes
User Data Fix broken production data @MarkKh
